### ISSUE TITLE
pretty printing from any format to a desire/customizble format

### ISSUE THREAD

**Issue by saly1365** [polytypic/prettier-printer#3]
Hey.
I am wondering if there is a way to convert a format to a desired format? here what I mean:
I have the following code--which is a graphviz input. 
` a -> b, c; 
c -> g, f [arrowhead = diamond]
`
and I want to have the following: 
`
a implies ( b and c)
c implies (g OR f)
`
I there any way to do so, or I got to write it myself?

Thanks

**Comment by polytypic** [comment]
For a conversion like that, you need to parse the input, which is not in the scope of this library.  Have you taken a look at parser combinator libraries?

**Comment by saly1365** [comment]
no. I have not.

**Comment by polytypic** [comment]
In case you are still working on this, it occurred to me that there are likely [ready made graphviz parsers for JS](https://www.google.com/search?q=javascript+graphviz+parser), which could be helpful for this problem.  Hope you'll get the conversion done!

At any rate, I'm closing this issue as parsing/format conversion isn't really in the scope of this library.
